/** AUTOGENERATED CODE BY GHOSTGRAPH CODEGEN **/

// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

struct PulseCreatedEvent {
    uint256 id;
    address author;
    string contentHash;
    uint256 timestamp;
}

struct ReactionAddedEvent {
    uint256 reactionId;
    uint256 pulseId;
    address reactor;
    string reactionType;
    uint256 timestamp;
}

struct WalletConnectedEvent {
    address user;
    uint256 timestamp;
}